### ISSUE TITLE
ARTAuthTokenParams: `ttl` type is not consistent with spec

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#131]
The type of `ARTAuthTokenParams.ttl` is [NSTimeInterval](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_DataTypes/index.html#//apple_ref/c/tdef/NSTimeInterval):
> Used to specify a time interval, in seconds.

I often use `uint64_t` type when I want to represent milliseconds. Some references: [Precise timing measurements](https://developer.apple.com/library/mac/qa/qa1398/_index.html)

**Reference:**
[TK2a](http://docs.ably.io/client-lib-development-guide/features/#TK2a)

**Tasks**
 - ~~change `ttl` type~~
 - ~~check `ARTDefault.ttl` as well~~
 - ~~check [RSA5](http://docs.ably.io/client-lib-development-guide/features/#RSA5)~~
 - ~~check [RSA9e](http://docs.ably.io/client-lib-development-guide/features/#RSA9e)~~
 - [ ] add a test:

>  I would like to see a test that requests a token valid for 24 hours, then checks that the token does indeed expire the following day 24 hours later (or within a minute of that).

**Comment by mattheworiordan** [comment]
> > The type of ARTAuthTokenParams.ttl is NSTimeInterval:
> Used to specify a time interval, in seconds.

I don't think that in itself is wrong, especially if that is a standard type, but we do need to ensure then that all serialisation to and from JSON / MsgPack when communicating with Ably is converted correctly

**Comment by tcard** [comment]
The reference says:

> it yields sub-millisecond precision over a range of 10,000 years.

So there's no problem with precision here. ([TK2a](http://docs.ably.io/client-lib-development-guide/features/#TK2a) is kind of fuzzy about it, though, because it says that it is "in milliseconds" but then specifies the type as "long", so it doesn't define to what extent times smaller than a millisecond should be significative; anyway, the milliseconds requirement is met by NSTimeInterval.)

I agree with @mattheworiordan. Translating to iOS' standards is mostly what we're doing all around.

**Comment by ricardopereira** [comment]
Fixed 1e330a7e
