### ISSUE TITLE
Duplicated history

### ISSUE THREAD

**Issue by levey** [ably/ably-ios#450]
There is an issue that, same history messages will exist in multiple pulling action.
For example:
1. client A is offline, publish 2 messages (messageA, messageB) in Dev Console.
2. client A connect to Ably, fetch history by history method of channel, got the message A and B.
3. disconnect and kill app.
4. open client A and connect to Ably, fetch history again, the message A and B will still exist in result.

**Comment by tcard** [comment]
Hi, @levey. This doesn't represent an error —it's how it's designed to work. History is persistent ([for some time](https://support.ably.io/support/solutions/articles/3000030059-how-long-are-messages-stored-for)), and currently Ably doesn't provide a way to "consume" messages the way you want.

You can simulate that behavior by keeping a "last read" timestamp persisted in your app every time you pull history, then using it as start date in further history query by specifying it in the `ARTDataQuery` object you pass to the `history` method.

**Comment by mattheworiordan** [comment]
Hi @levey, just to confirm what @tcard has said, we're a pub/sub service.  This means that we can have any number of publishers decoupled from any number of subscribers.  As such, it is by design that any number of users who subscribe or request history, will always receive all messages.  See https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern for more info.
