### ISSUE TITLE
SocketRocket/SRWebSocket.h file not found

### ISSUE THREAD

**Issue by EvgenyKarkan** [ably/ably-ios#463]
Hello team.
I'm trying to execute unit tests from `AblySpec` target, but while building it - I'm getting an error: 
`SocketRocket/SRWebSocket.h file not found` in `ARTWebSocketTransport+Private.h` header file.

My environment: 
`OS X EL Capitan 10.11.3 (15D21)`
`Xcode 7.3 (7D175)`
`CocoaPods 1.0.1` 
`master` branch

How can I fix that?

**Comment by tcard** [comment]
I can't reproduce this, although I've seen this failing too in Travis since [this build](https://travis-ci.org/ably/ably-ios/builds/144409949).

Could you tell me:

1. The contents of the folder `./Pods/SocketRocket/SocketRocket` inside your copy of the repo?
2. Whether changing `<...>` to `"..."` [in this line](https://github.com/ably/ably-ios/blob/master/Source/ARTWebSocketTransport+Private.h#L14) fixes it?

**Comment by EvgenyKarkan** [comment]
Sure,
- folder contains 3 source files (`SocketRocket.h, SRWebSocket.h, SRWebSocket.m`)
- replacing `<>` with `""` - unfortunately, did not help. 

I've attached link with the screenshot from Finder and Xcode.
https://monosnap.com/file/sqjcz6JUKVVvU2C5QJ8sm9MbXwCciq

**Comment by tcard** [comment]
I've just pushed to master a commit that should fix this. In short, things were working with my outdated version of CocoaPods but not with the latest ones. I've changed a bunch of random things I've found in the Internet about this issue and now it works. Could you confirm?

**Comment by EvgenyKarkan** [comment]
Thanks @tcard, everything is ok now, so confirmed & closed.

**Comment by Doipah** [comment]
#import <../SocketRocket/SocketRocket/NSRunLoop+SRWebSocket.h>
#import <../SocketRocket/SocketRocket/NSURLRequest+SRWebSocket.h>
#import <../SocketRocket/SocketRocket/SRSecurityPolicy.h>
#import <../SocketRocket/SocketRocket/SRWebSocket.h>
