### ISSUE TITLE
Occasionally getting "Attached timed out" when using [subscribeWithAttachCallback]

### ISSUE THREAD

**Issue by liuzhen2008** [ably/ably-ios#649]
As the title says,

I sometimes get an error returned saying "attach timed out" with [ARTErrorInfoStatusCode = 0].

So...

1. When does this occur? It looks random from our perspective

2. If it happens, what are the consequences in ignoring the error? Anything i need to do to recover form it?

**Comment by tcard** [comment]
This happens when the client tries to attach to a channel (this is a previous internal step after which the client can publish/subscribe to messages on the channel) but never gets a response back from the server.

This should only happen when transient errors occur, such as networking errors.

The consequence is that the channel won't receive or send any messages. You probably want to call `channel.attach` then. If the connection has moved to DISCONNECTED due to the networking error, then when CONNECTED again the attach will be retried. (This could happen automatically, really, but it isn't implemented in this library. I'll bring that up.)

**Comment by tcard** [comment]
Sorry, I just rechecked and what I said used to be right but it isn't anymore. You don't need to reattach manually; the channel will move to the SUSPENDED state, which will trigger a reattach attempt automatically. So in the end the error is just informative.

**Comment by liuzhen2008** [comment]
@tcard Cool. So I don't need to do anything!
